version: '3.8'

services:
  # Service de base de données PostgreSQL partagée
  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=motdepasse_securise
      - POSTGRES_DB=shared_db
    networks:
      - research-data-network

  # Traefik comme reverse proxy
  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "8080:8080" # Dashboard (accès local uniquement)
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json
    networks:
      - research-data-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"

volumes:
  postgres_data:

networks:
  research-data-network:
    driver: bridge

volumes:
  postgres_data:
  kobo_mongo_data:
  kobocat_media:
  kpi_media:
  solr_data: